// USER MODULE
export const USER_SERVICE_TOKEN = 'USER_SERVICE_TOKEN'
export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN'

// AUTH MODULE
export const AUTH_SERVICE_TOKEN = 'AUTH_SERVICE_TOKEN'
export const AUTH_REPOSITORY_TOKEN = 'AUTH_REPOSITORY_TOKEN'
